-- dim_payload — vault YAML provenance + first_seen.
-- Loaded from seeds/dim_payload_seed.csv (regenerated by
-- scripts/seed_dim_payload.py).

{{ config(materialized='table') }}

SELECT
    payload_id,
    name,
    category,
    references,
    tags,
    toDate(first_seen) AS first_seen
FROM {{ ref('dim_payload_seed') }}
